services:
  activemq:
    image: webcenter/activemq:latest
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ACTIVEMQ_NAME=activemq
      - ACTIVEMQ_USERNAME=
      - ACTIVEMQ_PASSWORD=